---
title: "RControl and Function"
output: html_notebook
---

Control structure:
if else 

```{r}
x <- 1
if (x>3){
  y <- 10
} else {
  y <- 0
}
print(y)
```
loop :
if else 

```{r}
for (i in 1:10){
  print(i)
}

```
```{r}
x <- c("a", "b", "c", "d")
for (i in 1:4){
  print(x[i])
}

for (i in seq_along(x)){
  print (x[i])
}
  
for (letter in x){
  print (letter)
}

for (i in 1:4) print(i)
```
Nested Loops --- Careful
```{r}

x <- matrix(1:6, 2, 3)

for (i in seq_len(nrow((x)))) {
  for (j in seq_len(ncol(x))) {
    print (x[i,j])
  }
}

```
While loops

```{r}
count <- 0
while(count<10){
  print (count)
  count <- count + 1
}

z <- 5 

while (z>=3 && z<=10) {
  print (z)
  coin <- rbinom(1,1,0.5)
  if(coin == 1) { ## random walk
    z <- z + 1
  } else {
      z <- z - 1
    }
}

```


```{r}

x0 <- 1
tol <- 1e-8

repeat {
  x1 <- computeEstimate()
  if (abs(x1-x0) < tol){
    break
  } else {
    x0 <- x1
  }
  }

for (x in c(1:100)){
  if (x <= 20) {
    next
  } else {
    if (x/10 == 10) print (x)
  }
}
```
FUNCTION

```{r}
above(10,1)

args(lm)
lm

args(paste)

x <- paste("foo", "bar", "crn", sep=numeric(666))
x
```

SCOPING RULES

NEED TO DIGGGGGG

optim, nlm and optimize

```{r}


make.NegLogLik <- function(data, fixed=c(F,F)) {
  params <- fixed
  function(p) {
    params[!fixed] <- p
    mu <- params[1]
    sigma <- prams[2]
    a<- -0.5*length(data)*log(2*pi*sigma^2)
    b <- -0.5*sum((data-mu)^2) / (sigma^2)
    -(a+b)
  }
}

set.seed(1); normals <- rnorm(100,1,2)
nLL <- make.NegLogLik(normals)
nLL

ls(environment(nLL))
```










