---
title: "Cleaning Data"
author: "Mathias"
date: "09/09/2020"
output: html_document
---



```{r setup, include=FALSE}

```


#### Subsetting and Sorting

```{r}
set.seed(13435)
X <- data.frame("var1"=sample(1:5),"var2"=sample(6:10), "var3"=sample(11:15))
X <- X[sample(1:5),];X$var2[c(1,3)]=NA
X
```
```{r}
X[,1]
X[,"var1"]
X[1:2, "var2"]

#Conditions
X[(X$var1<= 3 & X$var3>11),]
X[(X$var1<= 1 | X$var3 > 15),]

# Deal with NA
X[which(X$var2 > 1),]

# Sorting
sort(X$var1)
sort(X$var1, decreasing = TRUE)
sort(X$var2, decreasing = TRUE, na.last = TRUE)

# Order
X[order(X$var1, X$var3),]

# Ordering with Plyr

library(plyr)
arrange(X,var1)
arrange(X, desc(var1)) # decreasing

# Adding Rows and columns
X$var4 <- rnorm(5)
Y <- cbind(X, rnorm(5))

# Rename Col
colnames(Y)[5] <- "var5"
Y
```
##### Summarizing data

```{r}

if (!file.exists("./data")){dir.create("./data")}
fileURL <- "http://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"
download.file(fileURL, destfile = "./data/restaurants.csv", method = "curl")
restdata <- read.csv("./data/restaurants.csv")
```


```{r }
# Summaries
head(restdata)
tail(restdata)
summary(restdata)
str(restdata)

# Quantiles
quantile(restdata$councilDistrict,na.rm = T)
quantile(restdata$councilDistrict,probs = c(0.5,0.75,0.9))

# Tables
table(restdata$zipCode, useNA = "ifany")
table(restdata$councilDistrict,restdata$zipCode)

# Check for missing value
sum(is.na(restdata$councilDistrict))
any(is.na(restdata$councilDistrict))
all(restdata$zipCode>0)

# Row and columns sums
colSums(is.na(restdata))
all(colsums(is.na(restdata)==0)

# Values with specific characteristics
table(restdata$zipCode %in% c("21212"))
table(restdata$zipCode %in% c("21212", "21213"))

# Filter table with conditions in list
restdata[restdata$zipCode %in% c("21212", "21213"),]

# Cross Tabs
data("UCBAdmissions")
DF = as.data.frame(UCBAdmissions)
summary(DF)

xt <- xtabs(Freq ~ Gender + Admit, data=DF)
xt

# Flat tables
warpbreaks$replicate <- rep(1:9, len = 54)
xt = xtabs(breaks ~., data=warpbreaks)
xt

ftable(xt)

# Check Size
fakedata = rnorm(1e5)
object.size(fakedata)

```
##### Creating new data

```{r}
# Index

s1 <- seq(1,10,by=2); s1
s2 <- seq(1,10, length=3);s2
x<- c(1,2,5,8,10); seq_along(x)

# Create new variable by combining 2
restdata$nearMe = restdata$neighborhood %in% c("Roland Park", "Homeland")
colnames(restdata)

# Creating binary variable.names
restdata$zipWrong = ifelse(restdata$zipCode <0, TRUE, FALSE)
table(restdata$zipWrong, restdata$zipcode <0)

# Creating Categorical variable
restdata$zipGroups = cut(restdata$zipCode, breaks=quantile(restdata$zipCode))

table(restdata$zipGroups, restdata$zipCode)

library(Hmisc)
restdata$zipGroups = cut2(restdata$zipCode, g=4)
table(restdata$zipGroups)

# Creating Factor Variables = encoding
restdata$zcf <- factor(restdata$zipCode)
restdata$zcf[1:10]

yesno <- sample(c("yes", "no"), size=10, replace=TRUE)
yesnofac = factor(yesno, levels=c("yes","no"))
yesno
relevel(yesnofac, ref="yes")
as.numeric(yesnofac)

# Cutting produces facot variables
restdata$zipGroups = cut2(restdata$zipCode, g=4)
table(restdata$zipGroups)

# using mutate function
restdata2 = mutate(restdata, zipGroups=cut2(zipCode, g=4))
table(restdata2$zipGroups)

# Common transforms
# abs()
# sqrt()
# ceiling()
# floor()
# round()
# signif()
# cos()sin()log()log2()log10()exp()

```

#### Reshaping the data

The goal is tidy data

```{r}
#install.packages("reshape2")
library(reshape2)

head(mtcars)

# melting data
mtcars$carname <- rownames(mtcars)
carMelt <- melt(mtcars, id=c("carname", "gear", "cyl"), measure.vars = c("mpg", "hp"))
head(carMelt)
tail(carMelt)

# Casting data frames
cylDataCounts <- dcast(carMelt, cyl ~ variable)
cylDataCounts

cylDataMean <- dcast(carMelt, cyl ~ variable, mean)
cylDataMean

# Averaging Value
# method 1
head(InsectSprays)
tapply(InsectSprays$count, InsectSprays$spray, sum)

# method2
# Split
spIns = split(InsectSprays$count, InsectSprays$spray)
spIns

sprCount = lapply(spIns, sum)
sprCount

unlist(sprCount)

sapply(spIns, sum)

# method 3 plyr package
ddply(InsectSprays, .(spray), summarize, sum=sum(count))

spraySums <- ddply(InsectSprays, .(spray), summarize, sum=ave(count, FUN=sum))
dim(spraySums)

```

#### DPLYR

```{r}
library(dplyr)




```



