---
title: "DPLYR"
author: "Mathias"
date: "09/09/2020"
output: html_document
---

```{r setup, include=FALSE}

```

```{r}
library(dplyr)

dim(mtcars)
str(mtcars)
names(mtcars)
head(mtcars)

mtcars <- data.frame(mtcars)
mtcars.f <- filter(mtcars, mtcars$cyl>4)

# Arrange
mtcars.a <- arrange(mtcars, mtcars$cyl)
mtcars.ad <- arrange(mtcars, desc(mtcars$cyl) ) 

mtcars.rename <- rename

```

QUIZZ

1 - Agriculture
```{r}
url = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
download.file(url, destfile = "./data/agri.csv")
dat <- read.csv("./data/agri.csv")
head(dat)

agricultureLogical <- dat$ACR == 3 & dat$AGS ==6
agricultureLogical
which(agricultureLogical)[1:3]

```
2 - JPEG
```{r}
library(jpeg)
url = "https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg"
download.file(url, destfile = "./data/face.jpg", mode='wb')
myjpeg <- readJPEG("./data/face.jpg", native = TRUE)

paste(quantile(myjpeg,probs = 0.3)-638, quantile(myjpeg, probs = 0.8))


```
3 - Domestic
```{r}
url = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
download.file(url, destfile = "./data/domestic.csv")
domestic <- read.csv("./data/domestic.csv")

url2 = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
download.file(url2, destfile = "./data/zip.csv")
zip <- read.csv("./data/zip.csv")


# Clean

library(dplyr)
library(data.table)
domestic <- fread("./data/domestic.csv", skip = 5, nrows = 191, select = c(1,2,4,5),col.names = c("CountryCode", "Rank", "Economy", "Total"))

head(domestic)

head(zip)

datamerge <- merge(domestic, zip, by = "CountryCode")
head(datamerge)
datamerge <- arrange(datamerge,desc(Rank))
paste(nrow(datamerge), datamerge$Economy[13])

```
4

```{r}

head(datamerge)
library(dplyr)

datamerge_nonOECD <- datamerge[datamerge$Income.Group == "High income: nonOECD",]

datamerge_OECD <- datamerge[datamerge$Income.Group == "High income: OECD",]
datamerge_OECD

paste(mean(datamerge_nonOECD[,datamerge_nonOECD$Rank]), mean(datamerge_OECD[,datamerge_OECD$Rank]))
      


```
5 - 

```{r}
datamerge$Rank5 <- cut(datamerge$Rank, breaks=5)

table(datamerge$Rank5, datamerge$Income.Group)

```



